"""System-defined packaged defaults for MLflow-Monitor v0."""

from .builtin_contract import (
    SYSTEM_DEFAULT_CONTRACT_ID,
    SYSTEM_DEFAULT_DATA_SCOPE_CONTRACT_REF,
    SYSTEM_DEFAULT_EXECUTION_CONTRACT_REF,
    SYSTEM_DEFAULT_FEATURE_CONTRACT_REF,
    SYSTEM_DEFAULT_PERMISSIVE_CONTRACT_RAW,
    SYSTEM_DEFAULT_SCHEMA_CONTRACT_REF,
)
from .builtin_finding_policy import (
    SYSTEM_COMPATIBILITY_FINDING_POLICY,
    SYSTEM_COMPATIBILITY_FINDING_POLICY_ID,
    SYSTEM_COMPATIBILITY_FINDING_POLICY_VERSION,
)
from .builtin_recipes import SYSTEM_DEFAULT_RECIPE_ID

__all__ = [
    "SYSTEM_DEFAULT_CONTRACT_ID",
    "SYSTEM_DEFAULT_DATA_SCOPE_CONTRACT_REF",
    "SYSTEM_DEFAULT_EXECUTION_CONTRACT_REF",
    "SYSTEM_DEFAULT_FEATURE_CONTRACT_REF",
    "SYSTEM_DEFAULT_SCHEMA_CONTRACT_REF",
    "SYSTEM_DEFAULT_PERMISSIVE_CONTRACT_RAW",
    "SYSTEM_DEFAULT_RECIPE_ID",
    "SYSTEM_COMPATIBILITY_FINDING_POLICY",
    "SYSTEM_COMPATIBILITY_FINDING_POLICY_ID",
    "SYSTEM_COMPATIBILITY_FINDING_POLICY_VERSION",
]
